config/routes.rb
Timekeeper::Application.routes.draw do
  devise_for :users

  resources :events
  resources :therapists do
    resources :bills, except: [:update, :create]
  end
  resources :bills, only: [:show]
  resources :event_categories
  resources :clients
  resources :users
  resources :bill_items
  resources :event_category_prices
  resources :praxis_bills
  resources :notifications
  resources :torgs

  namespace :api do
    resources :bills, only: [:new, :edit, :update, :create]
    resources :events
    resources :clients
    resources :users
    resources :notifications, only: [:index]
    resources :missing_signatures, only: [:index]
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "events#index"
end

app/models/event_category.rb
# encoding: utf-8

class EventCategory < ActiveRecord::Base
  has_many :event_category_prices, dependent: :destroy
  has_many :events

  validates_presence_of :title, :abbrv, :sort_order, :color
  validates_uniqueness_of :title, :abbrv

  scope :active, -> { where(active: true) }
  default_scope order('sort_order asc')
end

app/controllers/event_categories_controller.rb
class EventCategoriesController < InheritedResources::Base

  def create
    create! { event_categories_path }
  end

  def update
    update! { event_categories_path }
  end

  def destroy
    if resource.events.any?
      redirect_to event_categories_path, alert: 'Event category used by events cannot be deleted'
    else
      destroy!
    end
  end

  private

  def resource_params
    params.require(:event_category).permit(:active, :title, :abbrv, :sort_order, :color)
  end

end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/views/event_categories/_form.html.haml
= simple_form_for(@event_category) do |f|
  = f.error_notification

  = f.input :active
  = f.input :title
  = f.input :abbrv
  = f.input :sort_order, hint: '0 is first, 99 last'
  = f.input :color, hint: 'Normal CSS color code. ie #ff0000'

  = f.button :submit
  = cancel_link event_categories_path

app/views/event_categories/edit.html.haml
%h1 Editing Event Category

= render 'form'

app/views/event_categories/index.html.haml
%table.table
  %caption Event Categories
  %thead
    %tr
      %th Active
      %th Title
      %th Abbrv
      %th Sort Order
      %th Color
      %th
      %th

  - @event_categories.each do |ec|
    %tr
      %td= tick_if ec.active
      %td= ec.title
      %td= ec.abbrv
      %td= ec.sort_order
      %td= color_box ec.color
      %td= edit_link edit_event_category_path(ec)
      %td= destroy_link ec

= new_link 'Add Event Category', new_event_category_path

app/views/event_categories/new.html.haml
%h1 New Event Category

= render 'form'