config/routes.rb
Timekeeper::Application.routes.draw do
  devise_for :users

  resources :events
  resources :therapists do
    resources :bills, except: [:update, :create]
  end
  resources :bills, only: [:show]
  resources :event_categories
  resources :clients
  resources :users
  resources :bill_items
  resources :event_category_prices
  resources :praxis_bills
  resources :notifications
  resources :torgs

  namespace :api do
    resources :bills, only: [:new, :edit, :update, :create]
    resources :events
    resources :clients
    resources :users
    resources :notifications, only: [:index]
    resources :missing_signatures, only: [:index]
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "events#index"
end

app/models/event_category_price.rb
class EventCategoryPrice < ActiveRecord::Base
  belongs_to :event_category

  acts_as_taggable_on :therapists

  validates_presence_of :title, :event_category_id

  scope :by_most_recent, -> { order('updated_at desc') }
  scope :for_therapist, ->(abbrv) { tagged_with(abbrv).by_most_recent }

end

app/controllers/event_category_prices_controller.rb
class EventCategoryPricesController < InheritedResources::Base

  def create
    create! { event_category_prices_path }
  end

  def update
    update! { event_category_prices_path }
  end

  private

  def collection
    @event_category_prices ||= end_of_association_chain.by_most_recent
  end

  def resource_params
    params.require(:event_category_price).permit(:title, :event_category_id, :price, :therapist_list)
  end
end

app/views/event_category_prices/_form.html.haml
= simple_form_for(@event_category_price) do |f|
  = f.error_notification

  = f.input :title
  = f.association :event_category
  = f.input :therapist_list, label: "Therapists (available list #{Therapist.abbreviations.join(', ')})"
  = f.input :price

  = f.button :submit
  = cancel_link event_category_prices_path

app/views/event_category_prices/edit.html.haml
%h1 Edit Price

= render 'form'

app/views/event_category_prices/index.html.haml
%table.table
  %caption Prices
  %thead
    %tr
      %th Title
      %th Event Category
      %th Therapists
      %th Price
      %th
      %th

  - @event_category_prices.each do |ecp|
    %tr
      %td= ecp.title
      %td= ecp.event_category.title
      %td= ecp.therapist_list
      %td= number_to_euro ecp.price
      %td= edit_link edit_event_category_price_path(ecp)
      %td= destroy_link ecp

= new_link 'Add Price', new_event_category_price_path

app/views/event_category_prices/new.html.haml
%h1 New Price

= render 'form'