config/routes.rb
Timekeeper::Application.routes.draw do
  devise_for :users

  resources :events
  resources :therapists do
    resources :bills, except: [:update, :create]
  end
  resources :bills, only: [:show]
  resources :event_categories
  resources :clients
  resources :users
  resources :bill_items
  resources :event_category_prices
  resources :praxis_bills
  resources :notifications
  resources :torgs

  namespace :api do
    resources :bills, only: [:new, :edit, :update, :create]
    resources :events
    resources :clients
    resources :users
    resources :notifications, only: [:index]
    resources :missing_signatures, only: [:index]
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "events#index"
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller.try(:current_user) },
          recipient: ->(controller, model) { model.therapist },
          params: {
              note: :title,
              who: :therapist_abbrv
          }

  belongs_to :praxis_bill
  belongs_to :therapist
  has_many :bill_items, dependent: :destroy, include: [:event, :client]

  accepts_nested_attributes_for :bill_items, allow_destroy: true

  validates_presence_of :billed_on, :number
  validates_uniqueness_of :number, scope: :therapist_id

  scope :by_most_recent, -> { order('billed_on desc') }
  scope :unbilled, -> { where(praxis_bill_id: nil) }

  delegate :full_name, to: :therapist, prefix: true
  delegate :abbrv, to: :therapist, prefix: true, allow_nil: true

  def self.last_bill_by(therapist)
    where(therapist_id: therapist).order('billed_on desc').first
  end

  def generate_number
    count = 0
    begin
      number = format_number(count)
      count += 1
    end while number_exists?(number)
    number
  end

  def total
    @total ||= bill_items.map(&:price).inject(0) { |memo, price| memo + price }
  end

  def title
    "Bill #{number}"
  end

  private

  def format_number(count)
    number = [therapist_abbrv, Date.current.to_s(:bill)].compact.join('-')
    number += sprintf("-%03d", count) if count && count > 0
    number
  end

  def number_exists?(number)
    Bill.where(therapist_id: therapist_id, number: number).count > 0
  end
end

app/controllers/api/bills_controller.rb
class Api::BillsController < ApplicationController
  respond_to :json
  inherit_resources

  def new
    render json: new_resource
  end

  def edit
    render json: resource
  end

  private

  def new_resource
    bill = Bill.new
    bill.therapist ||= therapist
    bill.billed_on ||= Date.current
    bill.number ||= bill.generate_number
    bill
  end

  def therapist
    current_user.therapist
  end

  def resource_params
    params.require(:bill).permit(:id, :billed_on, :therapist_id, :number,
                                 bill_items_attributes: [:id, :event_id, :_destroy])
  end
end

app/controllers/bills_controller.rb
class BillsController < InheritedResources::Base
  belongs_to :therapist, optional: true
  respond_to :pdf, :html

  def show
    respond_with(resource) do |format|
      format.pdf do
        filename = "bill_#{@bill.billed_on.to_s(:de)}.pdf"
        send_data render_to_string(:layout => false), {
            filename: filename,
            disposition: 'inline',
            type: :pdf
        }
      end
    end
  end

  private

  def collection
    @bills ||= end_of_association_chain.by_most_recent
  end
end

app/helpers/bills_helper.rb
# encoding: utf-8
module BillsHelper

  def bill_to_pdf(bill)
    content_for_prawn(page_layout: :portrait,
                      margin: [2.cm, 2.cm]) do |pdf|
      cover_page(pdf, bill)
      clients_page(pdf, bill)
    end
  end

  def cover_page(pdf, bill)
    pdf.font "Times-Roman"
    pdf.font_size(11)
    pdf.move_down(3.cm)
    pdf.text <<EOF
  An die
  Frühförderung Gütersloh – IFF Zeitzen
  Fröbelstr.32

  33330 Gütersloh








EOF
    table = [
        ['Re-Nr: IFF-Zeitzen', bill.number],
        [' ',' '],
        ['',"Gütersloh, den #{bill.billed_on.to_s(:de)}"]
    ]
    pdf.table(table,
              :width => pdf.bounds.width,
              cell_style: { borders: [] },
              :column_widths => [10.cm]) do
      cells.padding = 0
    end

    pdf.text <<EOF


  Sehr geehrte Damen und Herren,

  im Rahmen der Interdisziplinären Frühförderung Gütersloh – IFF Zeitzen stelle
  ich Ihnen folgende Rechnung:


EOF
    data = cover_table(bill)
    last_row = data.length - 1
    pdf.table(data,
              cell_style: { borders: [:top], border_widths: 0.1 }) do
      cells.padding = 3
      row(0).borders = []
      row(0).font_style = :bold
      row(last_row).font_style = :bold
      columns(1..3).align = :right
    end
    pdf.text <<EOF


Zahlen Sie den Rechnungsbetrag unter Angabe der Rechnungsnummer bitte auf
mein Konto bei der #{bill.therapist.bank}, Konto #{bill.therapist.konto_nr}, BLZ #{bill.therapist.blz}.
EOF
  end

  def cover_table(bill)
    table = []
    table << ['Behandlungsart', 'Zahl der Fördereinheiten', 'Preis je Einheit', 'Summe']
    bp = BillPresenter.new(bill)
    bp.services(all: true).each do |s|
      table << [s.name, s.qty, prawn_euro(s.price), prawn_euro(s.total)]
    end
    table << ['Gesamtbetrag', nil, nil, prawn_euro(bill.total)]
    table
  end

  def clients_page(pdf, bill)
    pdf.start_new_page(:size => "A4", :layout => :landscape)
    pdf.font "Times-Roman"
    pdf.font_size(11)
    pdf.text "Abrechnung Fördereinheiten #{bill.therapist.full_name} #{bill.billed_on.to_s(:de)}",
             size: 18, style: :bold
    pdf.text "\n"
    data = clients_table(bill)
    last_row = data.length - 1
    pdf.table(data,
              header: true,
              cell_style: { borders: [:top, :left, :right, :bottom], border_widths: 0.1 }) do
      cells.padding_left = 4
      cells.padding_right = 4
      cells.padding_top = 2
      cells.padding_bottom = 2
      cells.width = 2.5.cm
      cells.align = :center
      column(0).width = 5.cm
      row(0).borders = []
      row(0).font_style = :italic
      column(0).align = :left
      column(1).align = :center
      last_rows = (last_row-2)..last_row
      row(last_row-3).column(0).align = :right
      row(last_rows).align = :right
      row(last_row).font_style = :bold
    end
  end

  def clients_table(bill)
    bp = BillPresenter.new(bill)
    table = []
    table << (%w(Name Geburts-datum) + bp.service_names)
    bp.clients.each do |c|
      row = [c.full_name, c.dob]
      row += bp.service_abbrvs.map {|abbrv| c.services[abbrv].qty if c.services[abbrv]}
      table << row
    end
    table << (['Summe',''] + extract_services(bp, :qty){|i| i})
    table << (['Preis',''] + extract_services(bp, :price){|i| prawn_euro(i)})
    table << (['Teilsummen',''] + extract_services(bp, :total){|i| prawn_euro(i)})
    table << ['Gesamt', '', prawn_euro(bill.total)]
    table
  end

  def extract_services(bp, value, &block)
    bp.service_abbrvs.map do |abbrv|
      if bp.services[abbrv]
        yield bp.services[abbrv].send(value)
      end
    end
  end

  def prawn_euro(value)
    number_to_currency(value).to_s.gsub(/\s/, Prawn::Text::NBSP)
  end
end

app/views/bills/_bill.html.haml
.row
  -#= print_button('Verify Page', page: :verify)
  = print_button('Print Bill', page: :cover)

.title Bill #{bill.number}

.row
  .col-sm-2 Date:
  .col-sm-2
    %strong #{bill.billed_on.to_s(:de)}
.row
  .col-sm-2 Total
  .col-sm-2
    %strong #{number_to_euro bill.total}

- bp = BillPresenter.new(bill)

%table.table.therapist-bill-services.totals
  %thead
    %tr
      %th Behandlungsart
      %th Zahl der Fördereinheiten
      %th Preis je Einheit
      %th Summe
  %tbody
    - bp.services(all: true).each do |s|
      %tr
        %td= s.name
        %td= s.qty
        %td= number_to_euro s.price
        %td= number_to_euro s.total
    %tr.qty
      %td
      %td{colspan: 2} Gesamtbetrag:
      %td= number_to_euro bill.total

%small
  - columns = 2 + bp.service_abbrvs.count
  %table.table.table-condensed.therapist-bill-clients.totals
    %thead
      %tr
        %th Name
        %th Geburts-datum
        - bp.service_names.each do |name|
          %th= name
    %tbody
      - bp.clients.each do |c|
        %tr{data: {collapsible: true}}
          %td= client_name c
          %td= c.dob
          - bp.service_abbrvs.each do |abbrv|
            %td= c.services[abbrv].qty if c.services[abbrv]
        %tr.collapse
          %td{colspan: columns}
            - c.client.events_from_bill(bill).each do |event|
              = l event.occurred_on
              = event.event_category_title
              %br
      %tr.qty
        %td
        %td Summe
        - bp.service_abbrvs.each do |abbrv|
          %td= bp.services[abbrv].qty if bp.services[abbrv]
      %tr.price
        %td
        %td Preis
        - bp.service_abbrvs.each do |abbrv|
          %td= number_to_euro(bp.services[abbrv].price) if bp.services[abbrv]
      %tr.total
        %td
        %td Teilsummen
        - bp.service_abbrvs.each do |abbrv|
          %td= number_to_euro(bp.services[abbrv].total) if bp.services[abbrv]
      %tr.total
        %td
        %td Gesamt
        %td= number_to_euro bill.total

app/views/bills/_clients_page.html.haml
- bp = BillPresenter.new(bill)

%h3
  Abrechnung Fördereinheiten #{bill.therapist.full_name} #{bill.billed_on.to_s(:de)}

%table.table.therapist-bill-clients.totals
  %thead
    %tr
      %th Name
      %th Geburts-datum
      - bp.service_names.each do |name|
        %th= name
  %tbody
    - bp.clients.each do |c|
      %tr
        %td= client_name c
        %td= c.dob
        - bp.service_abbrvs.each do |abbrv|
          %td= c.services[abbrv].qty if c.services[abbrv]
    %tr.qty
      %td
      %td Summe
      - bp.service_abbrvs.each do |abbrv|
        %td= bp.services[abbrv].qty if bp.services[abbrv]
    %tr.price
      %td
      %td Preis
      - bp.service_abbrvs.each do |abbrv|
        %td= number_to_euro(bp.services[abbrv].price) if bp.services[abbrv]
    %tr.total
      %td
      %td Teilsummen
      - bp.service_abbrvs.each do |abbrv|
        %td= number_to_euro(bp.services[abbrv].total) if bp.services[abbrv]
    %tr.total
      %td
      %td Gesamt
      %td= number_to_euro bill.total

:javascript
  print();

app/views/bills/_cover_page.html.haml
%p
  An die
  %br
  Frühförderung Gütersloh – IFF Zeitzen
  %br
  Fröbelstr.32
  %br

%p
  33330 Gütersloh

Re-Nr: IFF-Zeitzen-W-
%strong #{bill.number}

.row
  .offset6
    Gütersloh, den #{bill.billed_on.to_s(:de)}

%p
  Sehr geehrte Damen und Herren,
%p
  im Rahmen der Interdisziplinären Frühförderung Gütersloh – IFF Zeitzen stelle
  %br
  ich Ihnen folgende Rechnung:

- bp = BillPresenter.new(bill)

%table.table.therapist-bill-services.totals
  %thead
    %tr
      %th Behandlungsart
      %th Zahl der Fördereinheiten
      %th Preis je Einheit
      %th Summe
  %tbody
    - bp.services(all: true).each do |s|
      %tr
        %td= s.name
        %td= s.qty
        %td= number_to_euro s.price
        %td= number_to_euro s.total
    %tr.qty
      %td
      %td{colspan: 2} Gesamtbetrag:
      %td= number_to_euro bill.total

Zahlen Sie den Rechnungsbetrag unter Angabe der Rechnungsnummer bitte auf
%br
mein Konto bei der
#{bill.therapist.bank},
Konto #{bill.therapist.konto_nr},
BLZ #{bill.therapist.blz}.


:javascript
  print();

app/views/bills/_edit.html.haml
.row
  .col-sm-6
    = simple_form_for([parent, @bill]) do |f|
      = f.error_notification

      .row
        .col-xs-5
          = datepicker_field(f, :billed_on)
      = f.input :number

      = f.button :submit
      = cancel_link(therapist_bills_path(parent))

#included
  = render 'included', bill_items: @bill.bill_items.by_name
#excluded
  = render 'excluded', bill_items: parent.unbilled_items(@bill.billed_on)

app/views/bills/_excluded.html.haml
.row
  .col-md-8
    %h4 Excluded Events
    %table.table.tablesorter.table-condensed
      %thead
        %tr
          %th Name
          %th Date
          %th Activity
          %th
      %tbody
        - bill_items.each do |bi|
          %tr[bi.event]
            %td= client_name bi.client, length: 30
            %td= bi.occurred_on.to_s(:de)
            %td= bi.event_category_title
            %td
              = form_for(bi, remote: true) do |f|
                = f.hidden_field :bill_id, value: @bill.id
                = f.hidden_field :event_id
                = f.submit 'Add', class: 'btn btn-sm btn-default'

app/views/bills/_form.html.haml
%div(ng-controller='billFormCtrl' ng-init="loadBill(#{@bill.id})")
  %h3(ng-show="inProgress" )
    LOADING

  .bill-step(ng-hide="inProgress" )
    %legend Step 1: Verify Bill Information
    %form.form-horizontal(name='billForm')
      .form-group
        %label.col-sm-2.control-label Billed On
        .col-md-3.col-sm-3
          %input.form-control(name='billedOn' ng-model='bill.billedOn' ng-required='true'
                              show-weeks="false" datepicker-popup="dd.MM.yyyy")
      .form-group
        %label.col-sm-2.control-label Number
        .col-md-3.col-sm-3
          %input.form-control(name='number' ng-model='bill.number' ng-required='true')

  .bill-step(ng-hide="inProgress" )
    %legend Step 2: Special Actions
    .row
      .col-sm-4
        %p
          %button.btn.btn-primary(ng-click="editBillItem()")
            %i.glyphicon.glyphicon-plus
            Create a New Activity
      .col-sm-4
        %p
          %button.btn.btn-primary(ng-click="markAll(true)")
            %i.glyphicon.glyphicon-plus
            Include All Activities
      .col-sm-4
        %p
          %button.btn.btn-primary(ng-click="markAll(false)")
            %i.glyphicon.glyphicon-minus
            Exclude All Activities


  %script(id='billItemTemplate.html' type='text/ng-template')
    .modal-header
      %h3(ng-show="billItem.eventId") Edit Activity
      %h3(ng-hide="billItem.eventId") Add Activity
    .modal-body
      %form(name='form')
        .form-group
          %input#select-client(tk-select2='' data-placeholder="Select Client" ng-model="billItem.client"
                 collection='bill.clients' ng-required="true" )
        .form-group
          %input#select-therapy(tk-select2='' data-placeholder='Select Activity' ng-model='billItem.category'
                 collection='bill.eventCategories' ng-required="true")
        .form-group
          %datepicker.bill-border(name='occurredOn' show-weeks="false"
                                  ng-model="billItem.occurredOn" ng-required="true")
    .modal-footer
      %button(class='btn btn-default' ng-click="$dismiss()") Cancel
      %button(class='btn btn-primary' ng-click='$close(billItem)' ng-disabled="form.$invalid") Submit


  .bill-step(ng-hide="inProgress" )
    %legend Step 3: Verify activities
    %p
      Review the activities below. Activities in the left column are included in this bill.
      Activities in the right column are excluded.  To toggle between columns click the activity.
    %p
      To edit an activity, first click the
      %i.glyphicon.glyphicon-edit
      icon near the name, and then select the activity to edit.
    %p
      To add a new activity click the
      %i.glyphicon.glyphicon-plus
      icon.

    .panel.panel-default(ng-repeat="clientId in clientOrder" id="client-{{clientId}}")
      .panel-heading
        {{clientHash[clientId].text}}
        .bill-item-buttons
          %button.btn.btn-default.add-event(ng-click="addBillItem(clientId)" )
            %i.glyphicon.glyphicon-plus
          %button.btn.btn-default.edit-event(ng-click="editEnabled=!editEnabled" ng-class="{active: editEnabled}" )
            %i.glyphicon.glyphicon-edit
      .panel-body
        .row
          .col-sm-6.col-xs-6
            .bill-item.event-included(ng-repeat='billItem in billItemsByClient[clientId] | filter:{included:true}'
                       id="event-{{billItem.eventId}}")
              .bill-item-content(style="background-color: {{billItem.category.color}}"
                                   ng-click="clickBillItem(editEnabled, billItem)")
                %span(tk-date-format="{{billItem.occurredOn}}" format='DD.MM')
                {{billItem.category.text}}
                %i.pull-right.glyphicon.glyphicon-edit.pull-right(ng-if="editEnabled")
          .col-sm-6.col-xs-6.bill-items-excluded
            .bill-item(ng-repeat='billItem in billItemsByClient[clientId] | filter:{included:false}'
                       id="event-{{billItem.eventId}}")
              .bill-item-content(style="background-color: {{billItem.category.color}}"
                                   ng-click="clickBillItem(editEnabled, billItem)")
                %span(tk-date-format="{{billItem.occurredOn}}" format='DD.MM')
                {{billItem.category.text}}
                %i.pull-right.glyphicon.glyphicon-edit.pull-right(ng-if="editEnabled")

  .bill-step(ng-hide="inProgress" )
    %legend Step 4: Summary
    %p
      Bill {{bill.number}} has {{activeClientIds().length}} clients and
      {{ matchedBillItems(true).length }} included activities.
      {{ matchedBillItems(false).length }} activities are excluded.

    %p
      %button.btn.btn-lg.btn-primary(ng-click="saveBill()" ng-disabled="billForm.$invalid || matchedBillItems(true).length == 0")
        Save Bill

app/views/bills/_included.html.haml
.row
  .col-md-8
    %h4 Included Events
    %table.table.tablesorter.xtable-bill-items.table-condensed
      %thead
        %tr
          %th Name
          %th Date
          %th Activity
          %th
      %tbody
        - bill_items.each do |bi|
          %tr[bi]
            %td= client_name bi.client, length: 30
            %td= bi.occurred_on.to_s(:de)
            %td= bi.event_category_title
            %td= link_to 'Remove', bi, method: :delete, class: 'btn btn-sm btn-default', remote: true

app/views/bills/_verify_page.html.haml
- bp = BillPresenter.new(bill)

%table.table
  %thead
    %tr
      %th Name
      %th Vorname
      %th Geburts-datum
      %th Billed Date
      - bp.service_names(all: true).each do |name|
        %th= name
  %tbody
    - bp.clients.each do |c|
      %tr
        %td= c.last_name
        %td= c.first_name
        %td= c.dob
        %td= bill.billed_on.to_s(:de)
        - bp.service_abbrvs.each do |abbrv|
          %td= c.services[abbrv].qty if c.services[abbrv]
    %tr.qty
      %td
      %td
      %td Summe
      - bp.service_abbrvs.each do |abbrv|
        %td= bp.services[abbrv].qty if bp.services[abbrv]
    %tr.price
      %td
      %td
      %td Preis
      - bp.service_abbrvs.each do |abbrv|
        %td= number_to_euro(bp.services[abbrv].price) if bp.services[abbrv]
    %tr.total
      %td
      %td
      %td Teilsummen
      - bp.service_abbrvs.each do |abbrv|
        %td= number_to_euro(bp.services[abbrv].total) if bp.services[abbrv]
    %tr.total
      %td
      %td
      %td Gesamt
      %td= number_to_euro bill.total

app/views/bills/edit.html.haml
= render 'form'

app/views/bills/index.html.haml
- entries = ActiveModel::ArraySerializer.new(@bills, each_serializer: D3BillSerializer)
.row(ng-init="bill.amount={entries:#{entries.to_json}}")
  .col-sm-12
    %strong Bill Totals
  .col-sm-12{style: 'height: 200px'}
    %fs-area(label="Euro" interpolate="true" bind="bill.amount")


.row
  .col-sm-1
    = new_link 'Add Bill', new_therapist_bill_path(parent)

.row
  .col-sm-8
    %table.table.table-responsive
      %caption Bills
      %tr
        %th Billed on
        %th Bill Number
        %th.money Total
        %th
        %th

      - @bills.each do |bill|
        %tr
          %td= bill.billed_on.to_s(:de)
          %td= link_to(bill.number, bill)
          = td_money(bill.total)
          %td.edit-link= edit_link edit_therapist_bill_path(parent, bill)
          %td.destroy-link= destroy_link([parent, bill])

app/views/bills/new.html.haml
= render 'form'

app/views/bills/show.html.haml
- if !printing?
  = render @bill
- else
  = render 'verify_page', bill: @bill if params[:page] == 'verify'

app/views/bills/show.pdf.haml
= bill_to_pdf(@bill)