config/routes.rb
Timekeeper::Application.routes.draw do
  devise_for :users

  resources :events
  resources :therapists do
    resources :bills, except: [:update, :create]
  end
  resources :bills, only: [:show]
  resources :event_categories
  resources :clients
  resources :users
  resources :bill_items
  resources :event_category_prices
  resources :praxis_bills
  resources :notifications
  resources :torgs

  namespace :api do
    resources :bills, only: [:new, :edit, :update, :create]
    resources :events
    resources :clients
    resources :users
    resources :notifications, only: [:index]
    resources :missing_signatures, only: [:index]
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "events#index"
end

app/models/praxis_bill.rb
class PraxisBill < ActiveRecord::Base
  belongs_to :user
  has_many :bills, dependent: :nullify
  has_many :bill_items, through: :bills
  has_many :events, through: :bill_items, include: [:client, :therapist, :event_category]

  validates_presence_of :billed_on, :number
  scope :by_most_recent, -> { order('billed_on desc') }

  def events_by_clients
    grouped = events.group_by do |event|
      event.client
    end
    grouped.keys.sort.map {|k| grouped[k] }
  end

end

app/controllers/praxis_bills_controller.rb
class PraxisBillsController < InheritedResources::Base

  def new
    unbilled_count = Bill.unbilled.count
    if unbilled_count == 0
      redirect_to praxis_bills_path, alert: t('praxis_bills.no_unbilled_therapist_bills',
                                              default: 'No unbilled therapist bills are available to select')
    else
      new!
    end
  end

  def create
    @praxis_bill = build_resource
    if @praxis_bill.bills.size == 0
      redirect_to praxis_bills_path, alert: t('praxis_bills.no_therapist_bills_selected',
                                              default: "Praxis bill was not created. No therapist bill was selected.")
      return
    end
    create!
  end

  private

  def collection
    @praxis_bills ||= end_of_association_chain.by_most_recent
  end

  private

  def resource_params
    params.require(:praxis_bill).permit(:billed_on, :number, :note, :bill_ids => [])
  end
end

app/views/praxis_bills/_form.html.haml
= simple_form_for(@praxis_bill, html: {class: 'form-horizontal'}) do |f|
  = f.error_notification
  = datepicker_field(f, :billed_on)
  = f.input :number
  = f.input :note, input_html: {cols: 80, rows: 5}
  = f.input :bill_ids, label: 'Therapist Bills Included:', as: :check_boxes, collection: (@praxis_bill.bills + Bill.unbilled).uniq

  = f.button :submit
  = cancel_link praxis_bills_path

app/views/praxis_bills/edit.html.haml
%h1 Editing bill

= render 'form'

app/views/praxis_bills/index.html.haml
.row
  .col-sm-8
    %table.table
      %caption Praxis Bills
      %thead
        %tr
          %th Billed On
          %th Bill Number
          %th Note
          %th Therapist Bills
          %th
          %th
      %tbody
        - @praxis_bills.each do |praxis_bill|
          %tr
            %td= l praxis_bill.billed_on
            %td= link_to(praxis_bill.number || '<no number>', praxis_bill)
            %td= praxis_bill.note
            %td
              - praxis_bill.bills.each do |bill|
                - therapist = bill.therapist
                - name = "#{therapist.abbrv} #{bill.number}"
                = link_to name, therapist_bill_path(bill.therapist, bill)
                %br
            %td= edit_link edit_praxis_bill_path(praxis_bill)
            %td= destroy_link praxis_bill

.row
  .col-sm-1
    = new_link 'Add Praxis Bill', new_praxis_bill_path

app/views/praxis_bills/new.html.haml
%h1 New bill

= render 'form'

app/views/praxis_bills/show.html.haml
.row
  .col-sm-8
    %table.table.table-bordered.table-praxis-bill
      %caption Praxis Bill #{@praxis_bill.number}
      %thead
        %tr
          %th Client
          %th Date
          %th Event
          %th Therapist
      %tbody
        - @praxis_bill.events_by_clients.each_with_index do |events, i|
          - zebra = i % 2 == 0 ? 'even' : ''
          - events.each do |event|
            %tr{class: zebra}
              %td= event.client_full_name
              %td= l event.occurred_on
              %td= event.event_category_title
              %td= event.therapist_full_name